export const guests = [
  {
    No: "1",
    Team: "Ban",
    Guest_Name: "Anh Thắng Nguyễn++ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "QW5oIFRoP25nIE5ndXk_bisrIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=QW5oIFRoP25nIE5ndXk_bisrIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_1_No_1.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "2",
    Team: "Ban",
    Guest_Name: "Bạn Đạt++ (Cấp 3)",
    Forms: "Bạn Nam",
    Guest_Code: "Qj9uINA_dCsrIChDP3AgMyk",
    URL: "https://namngoc.invite.io.vn/?name=Qj9uINA_dCsrIChDP3AgMyk",
    "QR name": "E:\\\\qrcodes\\\\qrcode_2_No_2.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "Yes",
    Party_3: "Yes",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "No",
    Departure_3: "Yes",
    Return_1: "No",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "3",
    Team: "Ban",
    Guest_Name: "Bạn Duy++ (Cấp 3)",
    Forms: "Bạn Nam",
    Guest_Code: "Qj9uIER1eSsrIChDP3AgMyk",
    URL: "https://namngoc.invite.io.vn/?name=Qj9uIER1eSsrIChDP3AgMyk",
    "QR name": "E:\\\\qrcodes\\\\qrcode_3_No_3.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "Yes",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "No",
    Departure_3: "Yes",
    Return_1: "No",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "4",
    Team: "Ban",
    Guest_Name: "Bạn My++ (Cấp 3)",
    Forms: "Bạn Nam",
    Guest_Code: "Qj9uIE15KysgKEM_cCAzKQ",
    URL: "https://namngoc.invite.io.vn/?name=Qj9uIE15KysgKEM_cCAzKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_4_No_4.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "Yes",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "No",
    Departure_3: "Yes",
    Return_1: "No",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "5",
    Team: "Ban",
    Guest_Name: "Bạn Nghĩa++ (Bách Khoa)",
    Forms: "Bạn Nam",
    Guest_Code: "Qj9uIE5naGlhKysgKELhY2ggS2hvYSk",
    URL: "https://namngoc.invite.io.vn/?name=Qj9uIE5naGlhKysgKELhY2ggS2hvYSk",
    "QR name": "E:\\\\qrcodes\\\\qrcode_5_No_5.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "Yes",
    Party_3: "Yes",
    Party_4: "Yes",
    Departure_1: "Yes",
    Departure_2: "No",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "6",
    Team: "Ban",
    Guest_Name: "Bạn Tính++ (Cấp 3)",
    Forms: "Bạn Nam",
    Guest_Code: "Qj9uIFTtbmgrKyAoQz9wIDMp",
    URL: "https://namngoc.invite.io.vn/?name=Qj9uIFTtbmgrKyAoQz9wIDMp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_6_No_6.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "Yes",
    Party_3: "Yes",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "No",
    Departure_3: "Yes",
    Return_1: "No",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "7",
    Team: "Ban",
    Guest_Name: "Vợ chồng b.Hường+ (Cấp 3)",
    Forms: "Bạn Nam",
    Guest_Code: "Vj8gY2g_bmcgYi5IdT9uZysgKEM_cCAzKQ",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgYi5IdT9uZysgKEM_cCAzKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_7_No_7.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "Yes",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "No",
    Departure_3: "Yes",
    Return_1: "No",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "8",
    Team: "CAD",
    Guest_Name: "Anh Nguyên Võ++ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "QW5oIE5ndXnqbiBW9SsrIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=QW5oIE5ndXnqbiBW9SsrIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_8_No_8.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "9",
    Team: "CAD",
    Guest_Name: "Anh Huy Hoàng++ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "QW5oIEh1eSBIb-BuZysrIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=QW5oIEh1eSBIb-BuZysrIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_9_No_9.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "10",
    Team: "CAD",
    Guest_Name: "Anh Toàn Nguyễn++ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "QW5oIFRv4G4gTmd1eT9uKysgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=QW5oIFRv4G4gTmd1eT9uKysgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_10_No_10.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "11",
    Team: "CAD",
    Guest_Name: "Vợ chồng a.Jimmy+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgYS5KaW1teSsgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgYS5KaW1teSsgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_11_No_11.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "12",
    Team: "CAD",
    Guest_Name: "Vợ chồng a.Nhuận+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgYS5OaHU_bisgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgYS5OaHU_bisgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_12_No_12.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "13",
    Team: "CAD",
    Guest_Name: "Vợ chồng aVũ+(Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgYVZ1KyhNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgYVZ1KyhNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_13_No_13.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "14",
    Team: "CKT-aHieu",
    Guest_Name: "Anh Du Lê ++(Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "QW5oIER1IEzqICsrKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=QW5oIER1IEzqICsrKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_14_No_14.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "15",
    Team: "CKT-aHieu",
    Guest_Name: "Anh Dũng Phan++ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "QW5oIER1bmcgUGhhbisrIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=QW5oIER1bmcgUGhhbisrIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_15_No_15.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "16",
    Team: "CKT-aHieu",
    Guest_Name: "Bạn Huy Dương++ (Marvell)",
    Forms: "Bạn Nam Bùi",
    Guest_Code: "Qj9uIEh1eSBEdW9uZysrIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=Qj9uIEh1eSBEdW9uZysrIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_16_No_16.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "17",
    Team: "CKT-aHieu",
    Guest_Name: "Khang Nguyễn++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "S2hhbmcgTmd1eT9uKysgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=S2hhbmcgTmd1eT9uKysgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_17_No_17.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "Yes",
    Party_3: "Yes",
    Party_4: "Yes",
    Departure_1: "Yes",
    Departure_2: "No",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "18",
    Team: "CKT-aHieu",
    Guest_Name: "Lâm Thái++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "TOJtIFRo4WkrKyAoTWFydmVsbCk",
    URL: "https://namngoc.invite.io.vn/?name=TOJtIFRo4WkrKyAoTWFydmVsbCk",
    "QR name": "E:\\\\qrcodes\\\\qrcode_18_No_18.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "19",
    Team: "CKT-aHieu",
    Guest_Name: "Lân Nguyễn++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "TOJuIE5ndXk_bisrIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=TOJuIE5ndXk_bisrIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_19_No_19.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "20",
    Team: "CKT-aHieu",
    Guest_Name: "Nghĩa Ngô++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "TmdoaWEgTmf0KysgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=TmdoaWEgTmf0KysgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_20_No_20.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "Yes",
    Party_3: "Yes",
    Party_4: "Yes",
    Departure_1: "Yes",
    Departure_2: "No",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "21",
    Team: "CKT-aHieu",
    Guest_Name: "Thành Trần++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "VGjgbmggVHI_bisrIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=VGjgbmggVHI_bisrIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_21_No_21.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "22",
    Team: "CKT-aHieu",
    Guest_Name: "Vợ chồng a.Hiếu Nguyễn+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgYS5IaT91IE5ndXk_bisgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgYS5IaT91IE5ndXk_bisgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_22_No_22.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "23",
    Team: "CKT-aHieu",
    Guest_Name: "Vợ chồng a.Nam Hồ+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgYS5OYW0gSD8rIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgYS5OYW0gSD8rIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_23_No_23.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "24",
    Team: "CKT-aHieu",
    Guest_Name: "Vợ chồng a.Tân Nguyễn+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgYS5U4m4gTmd1eT9uKyAoTWFydmVsbCk",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgYS5U4m4gTmd1eT9uKyAoTWFydmVsbCk",
    "QR name": "E:\\\\qrcodes\\\\qrcode_24_No_24.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "25",
    Team: "CKT-aNha",
    Guest_Name: "Anh Nguyên Nguyễn++ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "QW5oIE5ndXnqbiBOZ3V5P24rKyAoTWFydmVsbCk",
    URL: "https://namngoc.invite.io.vn/?name=QW5oIE5ndXnqbiBOZ3V5P24rKyAoTWFydmVsbCk",
    "QR name": "E:\\\\qrcodes\\\\qrcode_25_No_25.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "Yes",
    Party_3: "Yes",
    Party_4: "Yes",
    Departure_1: "Yes",
    Departure_2: "No",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "26",
    Team: "CKT-aNha",
    Guest_Name: "Duy Phạm++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "RHV5IFBoP20rKyAoTWFydmVsbCk",
    URL: "https://namngoc.invite.io.vn/?name=RHV5IFBoP20rKyAoTWFydmVsbCk",
    "QR name": "E:\\\\qrcodes\\\\qrcode_26_No_26.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "Yes",
    Party_3: "Yes",
    Party_4: "Yes",
    Departure_1: "Yes",
    Departure_2: "No",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "27",
    Team: "CKT-aNha",
    Guest_Name: "Vợ chồng a.Nhã Dương+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgYS5OaOMgRHVvbmcrIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgYS5OaOMgRHVvbmcrIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_27_No_27.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "28",
    Team: "CKT-aPhi",
    Guest_Name: "Anh Khánh Lê++ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "QW5oIEto4W5oIEzqKysgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=QW5oIEto4W5oIEzqKysgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_28_No_28.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "29",
    Team: "CKT-aPhi",
    Guest_Name: "Anh Tuấn Nguyễn++ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "QW5oIFR1P24gTmd1eT9uKysgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=QW5oIFR1P24gTmd1eT9uKysgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_29_No_29.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "30",
    Team: "CKT-aPhi",
    Guest_Name: "Bạn Khang Đỗ++ (Marvell)",
    Forms: "Bạn Nam Bùi",
    Guest_Code: "Qj9uIEtoYW5nINA_KysgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=Qj9uIEtoYW5nINA_KysgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_30_No_30.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "31",
    Team: "CKT-aPhi",
    Guest_Name: "Vợ chồng a.Phi Lê+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgYS5QaGkgTOorIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgYS5QaGkgTOorIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_31_No_31.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "32",
    Team: "CKT-aPhi",
    Guest_Name: "Tiến Phan++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "VGk_biBQaGFuKysgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=VGk_biBQaGFuKysgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_32_No_32.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "33",
    Team: "CKT-aPhi",
    Guest_Name: "Sang Phùng++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "U2FuZyBQaPluZysrIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=U2FuZyBQaPluZysrIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_33_No_33.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "34",
    Team: "CKT-aPhi",
    Guest_Name: "Tình Nguyễn++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "VOxuaCBOZ3V5P24rKyAoTWFydmVsbCk",
    URL: "https://namngoc.invite.io.vn/?name=VOxuaCBOZ3V5P24rKyAoTWFydmVsbCk",
    "QR name": "E:\\\\qrcodes\\\\qrcode_34_No_34.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "35",
    Team: "CKT-aPhi",
    Guest_Name: "Trung Nguyễn++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "VHJ1bmcgTmd1eT9uKysgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=VHJ1bmcgTmd1eT9uKysgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_35_No_35.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "36",
    Team: "CKT-aPhi",
    Guest_Name: "Quang Nguyễn++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "UXVhbmcgTmd1eT9uKysgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=UXVhbmcgTmd1eT9uKysgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_36_No_36.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "37",
    Team: "CKT-aPhi",
    Guest_Name: "Dũng Nguyễn++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "RHVuZyBOZ3V5P24rKyAoTWFydmVsbCk",
    URL: "https://namngoc.invite.io.vn/?name=RHVuZyBOZ3V5P24rKyAoTWFydmVsbCk",
    "QR name": "E:\\\\qrcodes\\\\qrcode_37_No_37.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "38",
    Team: "CKT-aPhi",
    Guest_Name: "Linh Trần++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "TGluaCBUcj9uKysgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=TGluaCBUcj9uKysgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_38_No_38.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "39",
    Team: "CKT-aRay",
    Guest_Name: "Vợ chồng a.Tiến Trần+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgYS5UaT9uIFRyP24rIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgYS5UaT9uIFRyP24rIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_39_No_39.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "40",
    Team: "CKT-aRay",
    Guest_Name: "Anh Đình Khanh++ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "QW5oINDsbmggS2hhbmgrKyAoTWFydmVsbCk",
    URL: "https://namngoc.invite.io.vn/?name=QW5oINDsbmggS2hhbmgrKyAoTWFydmVsbCk",
    "QR name": "E:\\\\qrcodes\\\\qrcode_40_No_40.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "41",
    Team: "DIG",
    Guest_Name: "Vợ chồng a.Cảnh Hà+ (Synopsys)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgYS5DP25oIEjgKyAoU3lub3BzeXMp",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgYS5DP25oIEjgKyAoU3lub3BzeXMp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_41_No_41.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "42",
    Team: "DIG",
    Guest_Name: "Vợ chồng a.Nhật Thái+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgYS5OaD90IFRo4WkrIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgYS5OaD90IFRo4WkrIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_42_No_42.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "43",
    Team: "HR",
    Guest_Name: "Vợ chồng chị Minh+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgY2g_IE1pbmgrIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgY2g_IE1pbmgrIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_43_No_43.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "44",
    Team: "LAY-cLinh",
    Guest_Name: "Chị Linh Cao++ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Q2g_IExpbmggQ2FvKysgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=Q2g_IExpbmggQ2FvKysgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_44_No_44.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "45",
    Team: "LAY-cLinh",
    Guest_Name: "Chị Xuân Bùi++ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Q2g_IFh14m4gQvlpKysgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=Q2g_IFh14m4gQvlpKysgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_45_No_45.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "46",
    Team: "LAY-cLinh",
    Guest_Name: "Vợ chồng chị Lý Trần+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgY2g_IEz9IFRyP24rIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgY2g_IEz9IFRyP24rIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_46_No_46.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "47",
    Team: "LAY-cLinh",
    Guest_Name: "Vợ chồng chị Phương Nguyễn+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgY2g_IFBodW9uZyBOZ3V5P24rIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgY2g_IFBodW9uZyBOZ3V5P24rIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_47_No_47.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "48",
    Team: "LAY-cLy",
    Guest_Name: "Vợ chồng chị Vi Nguyễn+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgY2g_IFZpIE5ndXk_bisgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgY2g_IFZpIE5ndXk_bisgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_48_No_48.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "49",
    Team: "LAY-cPhuong",
    Guest_Name: "Bạn Trâm Hà++ (Marvell)",
    Forms: "Bạn Nam Bùi",
    Guest_Code: "Qj9uIFRy4m0gSOArKyAoTWFydmVsbCk",
    URL: "https://namngoc.invite.io.vn/?name=Qj9uIFRy4m0gSOArKyAoTWFydmVsbCk",
    "QR name": "E:\\\\qrcodes\\\\qrcode_49_No_49.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "50",
    Team: "LAY-cPhuong",
    Guest_Name: "Chị Trinh Nguyễn++ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Q2g_IFRyaW5oIE5ndXk_bisrIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=Q2g_IFRyaW5oIE5ndXk_bisrIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_50_No_50.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "51",
    Team: "LAY-cPhuong",
    Guest_Name: "Vợ chồng chị Phương Võ+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgY2g_IFBodW9uZyBW9SsgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgY2g_IFBodW9uZyBW9SsgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_51_No_51.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "52",
    Team: "LAY-cPhuong",
    Guest_Name: "Vợ chồng chị Trinh Lê+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgY2g_IFRyaW5oIEzqKyAoTWFydmVsbCk",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgY2g_IFRyaW5oIEzqKyAoTWFydmVsbCk",
    "QR name": "E:\\\\qrcodes\\\\qrcode_52_No_52.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "53",
    Team: "Lay-cPhuong",
    Guest_Name: "Thư Nguyễn++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "VGh1IE5ndXk_bisrIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=VGh1IE5ndXk_bisrIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_53_No_53.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "54",
    Team: "LAY-cLinh",
    Guest_Name: "Thúy Ngô++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "VGj6eSBOZ_QrKyAoTWFydmVsbCk",
    URL: "https://namngoc.invite.io.vn/?name=VGj6eSBOZ_QrKyAoTWFydmVsbCk",
    "QR name": "E:\\\\qrcodes\\\\qrcode_54_No_54.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "55",
    Team: "LAY-cLinh",
    Guest_Name: "Trang Lê++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "VHJhbmcgTOorKyAoTWFydmVsbCk",
    URL: "https://namngoc.invite.io.vn/?name=VHJhbmcgTOorKyAoTWFydmVsbCk",
    "QR name": "E:\\\\qrcodes\\\\qrcode_55_No_55.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "56",
    Team: "LAY-cLinh",
    Guest_Name: "Bạn Nhi Lê++ (Marvell)",
    Forms: "Bạn Nam Bùi",
    Guest_Code: "Qj9uIE5oaSBM6isrIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=Qj9uIE5oaSBM6isrIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_56_No_56.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "57",
    Team: "LAY-cLinh",
    Guest_Name: "Ngọc Lê++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "Tmc_YyBM6isrIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=Tmc_YyBM6isrIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_57_No_57.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "58",
    Team: "PM",
    Guest_Name: "Chị Phương Trương++ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Q2g_IFBodW9uZyBUcnVvbmcrKyAoTWFydmVsbCk",
    URL: "https://namngoc.invite.io.vn/?name=Q2g_IFBodW9uZyBUcnVvbmcrKyAoTWFydmVsbCk",
    "QR name": "E:\\\\qrcodes\\\\qrcode_58_No_58.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "59",
    Team: "PM",
    Guest_Name: "Trâm Phạm++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "VHLibSBQaD9tKysgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=VHLibSBQaD9tKysgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_59_No_59.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "60",
    Team: "LAY-cPhuong",
    Guest_Name: "Duyên Nguyễn++ (Marvell)",
    Forms: "Anh Nam Bùi",
    Guest_Code: "RHV56m4gTmd1eT9uKysgKE1hcnZlbGwp",
    URL: "https://namngoc.invite.io.vn/?name=RHV56m4gTmd1eT9uKysgKE1hcnZlbGwp",
    "QR name": "E:\\\\qrcodes\\\\qrcode_60_No_60.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    No: "61",
    Team: "LAY",
    Guest_Name: "Vợ chồng a.Lộc Hồ+ (Marvell)",
    Forms: "Em Nam Bùi",
    Guest_Code: "Vj8gY2g_bmcgYS5MP2MgSD8rIChNYXJ2ZWxsKQ",
    URL: "https://namngoc.invite.io.vn/?name=Vj8gY2g_bmcgYS5MP2MgSD8rIChNYXJ2ZWxsKQ",
    "QR name": "E:\\\\qrcodes\\\\qrcode_61_No_61.png",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
];
