export const guests = [
  {
    Guest_Name: "Vợ chồng a Nhật Châu",
    id: 1,
    Guest_Code: "ABCE",
    Friend: "Bride",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "Yes",
    Party_3: "No",
    Party_4: "Yes",
    Departure_1: "No",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "No",
    Return_3: "No",
  },
  {
    Guest_Name: "Vợ chồng bạn Thảo",
    id: 2,
    Guest_Code: "ABCD",
    Friend: "Bride",
    Invite_Side: "Bride",
    Party_1: "Yes",
    Party_2: "Yes",
    Party_3: "No",
    Party_4: "No",
    Departure_1: "No",
    Departure_2: "No",
    Departure_3: "Yes",
    Return_1: "No",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    Guest_Name: "Vợ chồng bạn Lĩnh",
    id: 3,
    Guest_Code: "ABCF",
    Friend: "Groom",
    Invite_Side: "Groom",
    Party_1: "No",
    Party_2: "No",
    Party_3: "Yes",
    Party_4: "Yes",
    Departure_1: "Yes",
    Departure_2: "Yes",
    Departure_3: "Yes",
    Return_1: "Yes",
    Return_2: "Yes",
    Return_3: "No",
  },
  {
    Guest_Name: "Duy",
    id: 4,
    Guest_Code: "ACDD",
    Friend: "Groom",
    Invite_Side: "Bride",
    Party_1: "No",
    Party_2: "Yes",
    Party_3: "Yes",
    Party_4: "Yes",
    Departure_1: "Yes",
    Departure_2: "No",
    Departure_3: "Yes",
    Return_1: "No",
    Return_2: "No",
    Return_3: "Yes",
  },
];
